version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: python-backend
    ports:
      - "8000:8000"
    volumes:
      - .env:/app/.env
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
      #command: python local.py
    networks:
      - custom_network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - .env:/app/.env
    command: npm start
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge

